CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
DEFAULT_REF_START_TOKEN = "<ref>"
DEFAULT_REF_END_TOKEN = "</ref>"
DEFAULT_BOX_START_TOKEN = "<box>"
DEFAULT_BOX_END_TOKEN = "</box>"
IMAGE_PLACEHOLDER = "<image-placeholder>"
